"use strict"; // treat all JS code as newer version

// alert(3 + 3)  // we are using nodejs, not browser

let name = "Sujeet"
let age = 25
let isLoggedIn = false
let state;

// there are two type to data types 

// 1- primitive datatype(non mutable)
// number => 2 to power 53
// bigint
// string => ""
// boolean => true/false
// null => standalone value  or empty value or no value
// undefined => value not assaind yet  or  a declared variable without a value
// symbol => unique or  A unique value that can be generated by Symbol constructor

// 2- non primitive datatype (mutable)
// Osbject
// Arrays

console.log(typeof undefined); // undefined
console.log(typeof null); // object